package models

type Application struct {
	ID         int    `json:"id" gorm:"type:uuid;primary_key;autoIncrement"`
	Description string `json:"description" gorm:"type:varchar(50)"`
	UserEmail     string    `json:"user_email" gorm:"type:varchar(50)"`
}

var regions = []string{
	"Adygey",
	"Altay",
	"Amur",
	"Arkhangel`sk",
	"Astrakhan",
	"Bashkortostan",
	"Belgorod",
	"Bryansk",
	"Buryat",
	"Chechnya",
	"Chelyabinsk",
	"Chukot",
	"Chuvash",
	"Dagestan",
	"Gorno-Altay",
	"Ingush",
	"Irkutsk",
	"Ivanovo",
	"Kabardin-Balkar",
	"Karachay-Cherkess",
	"Krasnodar",
	"Kemerovo",
	"Kaluga",
	"Khabarovsk",
	"Karelia",
	"Khakass",
	"Kalmyk",
	"Khanty-Mansiy",
	"Kaliningrad",
	"Komi",
	"Kamchatka",
	"Kursk",
	"Kostroma",
	"Kurgan",
	"Kirov",
	"Krasnoyarsk",
	"Leningrad",
	"Lipetsk",
	"Moscow City",
	"Mariy-El",
	"Magadan",
	"Murmansk",
	"Mordovia",
	"Moskva",
	"Novgorod",
	"Nenets",
	"North Ossetia",
	"Novosibirsk",
	"Nizhegorod",
	"Orenburg",
	"Orel",
	"Omsk",
	"Perm",
	"Primor`ye",
	"Pskov",
	"Penza",
	"Rostov",
	"Ryazan",
	"Samara",
	"Sakha",
	"Sakhalin",
	"Smolensk",
	"Saint Petersburg City",
	"Saratov",
	"Stavropol",
	"Sverdlovsk",
	"Tambov",
	"Tomsk",
	"Tula",
	"Tatarstan",
	"Tuva",
	"Tver",
	"Tyumen",
	"Udmurt",
	"Ul`yanovsk",
	"Volgograd",
	"Vladimir",
	"Yamal-Nenets",
	"Vologda",
	"Voronezh",
	"Yaroslavl",
	"Yevrey",
	"Zabaykal`ye",
}
